name: TruffleHog Scan 2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@add-actions-cli-switch
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified
      
      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
