# aws_config.py

AWS_ACCESS_KEY_ID = "AKIAXXXEXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
REGION_NAME = "us-west-2"

AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
AWS_SESSION_TOKEN=AQoDYXdzEJr1KexampleMRYr7+K9WuYEXAMPLEPp9TefkXr3sXplJ7Nh1examplexYhYHk/qXCpFtXyExample3+fwZdjVQ==
