# ssl_config.py

SSL_CERTIFICATE = """
-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJALa5fXhK6JmSMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApyb2NrZXQgc2NpZW5jZTEMMAoGA1UECgwDZmFrZTEN
MAsGA1UEAwwEcm9vdDAeFw0yMTA4MTIwNzU3MTJaFw0zMTA4MTAwNzU3MTJaMEUx
CzAJBgNVBAYTAkFVMRMwEQYDVQQIDApyb2NrZXQgc2NpZW5jZTEMMAoGA1UECgwD
ZmFrZTENMAsGA1UEAwwEcm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBALF2Lj48I6D1oF5k1H/Jl3LV39Q1sQ2KQz7VrCzxx/fxoxlcUMgWbduzB7/J
...
-----END CERTIFICATE-----
"""

SSL_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBeMwggXfAgEAAoIBAKpZt0hWQ3Wx9tCg
U9Oghz1+7IKDFHOqld6bf6D6KP4ljzpazXYL7MFFzsw6zZj/Pn1Oj9mdhx9d9+JS
...
-----END PRIVATE KEY-----
"""
