name: Detect-Secrets Scan CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install detect-secrets
        run: |
          sudo pip install detect-secrets

      - name: Run detect-secrets
        id: detect-secrets
        run: detect-secrets scan .

      - name: Finalize
        if: always()
        run: echo "detect-secrets scan completed."
