name: GitGuardian Secrets Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitguardian-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitGuardian CLI
        run: |
          pip install ggshield

      - name: Run GitGuardian Scan
        id: gitguardian
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GG_TOKEN }}
        run: |
          ggshield scan repo .

      - name: Finalize
        if: always()
        run: echo "GitGuardian scan completed."
