name: Git-Secrets Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  git-secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets && sudo make install
          git secrets --register-aws

      - name: Scan for secrets
        run: |
          git secrets --scan
