name: Gitleaks Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.6
