name: Git-secrets Scan CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitsecrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Git-secrets
        run: |
          # Install Git-secrets 1.3.0
          wget -qO- https://github.com/awslabs/git-secrets/releases/download/1.3.0/git-secrets-1.3.0.tar.gz | tar xvz
          cd git-secrets-1.3.0 && sudo make install

      - name: Run Git-secrets
        id: gitsecrets
        run: |
          git secrets --scan --recurse --no-textconv --allowed --signoff

      - name: Display Git-secrets Report
        if: success()
        run: |
          git secrets --scan --recurse --no-textconv --allowed --signoff

      - name: Finalize
        if: always()
        run: echo "Git-secrets scan completed."
