name: TruffleHog Scan CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TruffleHog
        run: |
          python3 -m pip install trufflehog

      - name: Run TruffleHog
        id: trufflehog
        run: trufflehog .
